// Code generated by go-swagger; DO NOT EDIT.

package transport

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/JunkieJI/travel-senpai/api/swagger/models"
)

// GetTransportByIDOKCode is the HTTP code returned for type GetTransportByIDOK
const GetTransportByIDOKCode int = 200

/*GetTransportByIDOK get transport by Id o k

swagger:response getTransportByIdOK
*/
type GetTransportByIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.Tranport `json:"body,omitempty"`
}

// NewGetTransportByIDOK creates GetTransportByIDOK with default headers values
func NewGetTransportByIDOK() *GetTransportByIDOK {
	return &GetTransportByIDOK{}
}

// WithPayload adds the payload to the get transport by Id o k response
func (o *GetTransportByIDOK) WithPayload(payload *models.Tranport) *GetTransportByIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get transport by Id o k response
func (o *GetTransportByIDOK) SetPayload(payload *models.Tranport) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTransportByIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
