-- MySQL Script generated by MySQL Workbench
-- Sun Dec 24 17:44:04 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema travel_senpai
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema travel_senpai
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `travel_senpai` DEFAULT CHARACTER SET utf8 ;
USE `travel_senpai` ;

-- -----------------------------------------------------
-- Table `travel_senpai`.`account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `travel_senpai`.`account` (
  `id` INT NOT NULL,
  `name` VARCHAR(100) NULL,
  `email` VARCHAR(100) NULL,
  `username` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `travel_senpai`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `travel_senpai`.`user` (
  `id` INT NOT NULL,
  `account_id` INT NOT NULL,
  `collection_id` INT NOT NULL,
  PRIMARY KEY (`id`, `collection_id`),
  INDEX `fk_users_accounts1_idx` (`account_id` ASC),
  CONSTRAINT `fk_users_accounts1`
    FOREIGN KEY (`account_id`)
    REFERENCES `travel_senpai`.`account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `travel_senpai`.`destination`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `travel_senpai`.`destination` (
  `id` INT NOT NULL,
  `budget` INT NULL,
  `country` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `currency` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `travel_senpai`.`trip`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `travel_senpai`.`trip` (
  `id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
