swagger: '2.0'
info:
  version: ''
  title: Dashboard
  description: ''
host: 'localhost:3000'
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  '/transport/{id}':
    parameters:
      - name: id
        in: path
        required: true
        type: string
    get:
      operationId: GetTransportByID
      summary: Get Transport By ID
      tags:
        - Transport
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/tranport'
  /trips:
    get:
      operationId: GetTrips
      summary: Trips
      tags:
        - trip
        - Trips
      responses:
        '200':
          description: ''
          schema:
            type: array
            items:
              $ref: '#/definitions/trip'
        '400':
          $ref: '#/responses/trait:global:400'
        '404':
          $ref: '#/responses/trait:global:404'
        '500':
          $ref: '#/responses/trait:global:500'
  '/trips/{id}':
    parameters:
      - name: id
        in: path
        required: true
        type: integer
    get:
      operationId: GetTripByID
      summary: Trip By ID
      tags:
        - trip
        - Trips
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/trip'
          examples:
            application/json:
              '': pariatur do dolore
        '400':
          $ref: '#/responses/trait:global:400'
        '404':
          $ref: '#/responses/trait:global:404'
        '500':
          $ref: '#/responses/trait:global:500'
  /destinations:
    get:
      operationId: GetDestinations
      summary: Destinations
      tags:
        - Destinations
      responses:
        '200':
          description: ''
          schema:
            type: array
            items:
              $ref: '#/definitions/destination'
        '400':
          $ref: '#/responses/trait:global:400'
        '404':
          $ref: '#/responses/trait:global:404'
        '500':
          $ref: '#/responses/trait:global:500'
    post:
      operationId: CreateDestination
      summary: Create Destination
      tags:
        - Destinations
      parameters:
        - name: body
          in: body
          schema:
            $ref: '#/definitions/destination'
        - name: Accept-Languge
          in: header
          type: string
      responses:
        '201':
          description: ''
          schema:
            $ref: '#/definitions/destination'
        '400':
          $ref: '#/responses/trait:global:400'
        '404':
          $ref: '#/responses/trait:global:404'
        '500':
          $ref: '#/responses/trait:global:500'
  '/destinations/{id}':
    parameters:
      - name: id
        in: path
        required: true
        type: integer
    get:
      operationId: GetDestinationByID
      summary: Destination By ID
      tags:
        - Destinations
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/destination'
        '400':
          $ref: '#/responses/trait:global:400'
        '404':
          $ref: '#/responses/trait:global:404'
        '500':
          $ref: '#/responses/trait:global:500'
    put:
      operationId: UpdateDestination
      summary: Update Destination
      tags:
        - Destinations
      parameters:
        - name: body
          in: body
          schema:
            $ref: '#/definitions/destination'
        - name: Accept-Language
          in: header
          type: string
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/destination'
        '400':
          $ref: '#/responses/trait:global:400'
        '404':
          $ref: '#/responses/trait:global:404'
        '500':
          $ref: '#/responses/trait:global:500'
    delete:
      operationId: DeleteDestinationByID
      summary: Delete Destination By ID
      tags:
        - Destinations
      responses:
        '204':
          description: ''
          schema:
            type: string
        '400':
          $ref: '#/responses/trait:global:400'
        '404':
          $ref: '#/responses/trait:global:404'
        '500':
          $ref: '#/responses/trait:global:500'
responses:
  'trait:global:400':
    description: ''
    schema:
      type: string
  'trait:global:404':
    description: ''
    schema:
      type: string
  'trait:global:500':
    description: ''
    schema:
      type: string
definitions:
  trip:
    title: Trip
    type: object
    properties:
      id:
        type: integer
  destination:
    title: Destination
    type: object
    properties:
      id:
        type: integer
      budget:
        type: integer
      country:
        type: string
      city:
        type: string
      currency:
        type: string
  tranport:
    title: Tranport
    type: object
    properties:
      id:
        type: integer
      destination_id:
        type: integer
      type:
        type: string
      departure_date:
        type: string
      departure_time:
        type: string
      arrival_date:
        type: string
      arrival_time:
        type: string
      layover:
        type: string
      cost:
        type: integer