// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Dashboard

    Schemes:
      http
    Host: localhost:3000
    BasePath: /

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
