// Code generated by go-swagger; DO NOT EDIT.

package destinations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// CreateDestinationHandlerFunc turns a function with the right signature into a create destination handler
type CreateDestinationHandlerFunc func(CreateDestinationParams) middleware.Responder

// Handle executing the request and returning a response
func (fn CreateDestinationHandlerFunc) Handle(params CreateDestinationParams) middleware.Responder {
	return fn(params)
}

// CreateDestinationHandler interface for that can handle valid create destination params
type CreateDestinationHandler interface {
	Handle(CreateDestinationParams) middleware.Responder
}

// NewCreateDestination creates a new http.Handler for the create destination operation
func NewCreateDestination(ctx *middleware.Context, handler CreateDestinationHandler) *CreateDestination {
	return &CreateDestination{Context: ctx, Handler: handler}
}

/*CreateDestination swagger:route POST /destinations Destinations createDestination

Create Destination

*/
type CreateDestination struct {
	Context *middleware.Context
	Handler CreateDestinationHandler
}

func (o *CreateDestination) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewCreateDestinationParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
