// Code generated by go-swagger; DO NOT EDIT.

package destinations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteDestinationByIDNoContentCode is the HTTP code returned for type DeleteDestinationByIDNoContent
const DeleteDestinationByIDNoContentCode int = 204

/*DeleteDestinationByIDNoContent delete destination by Id no content

swagger:response deleteDestinationByIdNoContent
*/
type DeleteDestinationByIDNoContent struct {
}

// NewDeleteDestinationByIDNoContent creates DeleteDestinationByIDNoContent with default headers values
func NewDeleteDestinationByIDNoContent() *DeleteDestinationByIDNoContent {
	return &DeleteDestinationByIDNoContent{}
}

// WriteResponse to the client
func (o *DeleteDestinationByIDNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(204)
}

// DeleteDestinationByIDBadRequestCode is the HTTP code returned for type DeleteDestinationByIDBadRequest
const DeleteDestinationByIDBadRequestCode int = 400

/*DeleteDestinationByIDBadRequest delete destination by Id bad request

swagger:response deleteDestinationByIdBadRequest
*/
type DeleteDestinationByIDBadRequest struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewDeleteDestinationByIDBadRequest creates DeleteDestinationByIDBadRequest with default headers values
func NewDeleteDestinationByIDBadRequest() *DeleteDestinationByIDBadRequest {
	return &DeleteDestinationByIDBadRequest{}
}

// WithPayload adds the payload to the delete destination by Id bad request response
func (o *DeleteDestinationByIDBadRequest) WithPayload(payload string) *DeleteDestinationByIDBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete destination by Id bad request response
func (o *DeleteDestinationByIDBadRequest) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteDestinationByIDBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// DeleteDestinationByIDNotFoundCode is the HTTP code returned for type DeleteDestinationByIDNotFound
const DeleteDestinationByIDNotFoundCode int = 404

/*DeleteDestinationByIDNotFound delete destination by Id not found

swagger:response deleteDestinationByIdNotFound
*/
type DeleteDestinationByIDNotFound struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewDeleteDestinationByIDNotFound creates DeleteDestinationByIDNotFound with default headers values
func NewDeleteDestinationByIDNotFound() *DeleteDestinationByIDNotFound {
	return &DeleteDestinationByIDNotFound{}
}

// WithPayload adds the payload to the delete destination by Id not found response
func (o *DeleteDestinationByIDNotFound) WithPayload(payload string) *DeleteDestinationByIDNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete destination by Id not found response
func (o *DeleteDestinationByIDNotFound) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteDestinationByIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// DeleteDestinationByIDInternalServerErrorCode is the HTTP code returned for type DeleteDestinationByIDInternalServerError
const DeleteDestinationByIDInternalServerErrorCode int = 500

/*DeleteDestinationByIDInternalServerError delete destination by Id internal server error

swagger:response deleteDestinationByIdInternalServerError
*/
type DeleteDestinationByIDInternalServerError struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewDeleteDestinationByIDInternalServerError creates DeleteDestinationByIDInternalServerError with default headers values
func NewDeleteDestinationByIDInternalServerError() *DeleteDestinationByIDInternalServerError {
	return &DeleteDestinationByIDInternalServerError{}
}

// WithPayload adds the payload to the delete destination by Id internal server error response
func (o *DeleteDestinationByIDInternalServerError) WithPayload(payload string) *DeleteDestinationByIDInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete destination by Id internal server error response
func (o *DeleteDestinationByIDInternalServerError) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteDestinationByIDInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}
