// Code generated by go-swagger; DO NOT EDIT.

package destinations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetDestinationsHandlerFunc turns a function with the right signature into a get destinations handler
type GetDestinationsHandlerFunc func(GetDestinationsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetDestinationsHandlerFunc) Handle(params GetDestinationsParams) middleware.Responder {
	return fn(params)
}

// GetDestinationsHandler interface for that can handle valid get destinations params
type GetDestinationsHandler interface {
	Handle(GetDestinationsParams) middleware.Responder
}

// NewGetDestinations creates a new http.Handler for the get destinations operation
func NewGetDestinations(ctx *middleware.Context, handler GetDestinationsHandler) *GetDestinations {
	return &GetDestinations{Context: ctx, Handler: handler}
}

/*GetDestinations swagger:route GET /destinations Destinations getDestinations

Destinations

*/
type GetDestinations struct {
	Context *middleware.Context
	Handler GetDestinationsHandler
}

func (o *GetDestinations) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetDestinationsParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
