// Code generated by go-swagger; DO NOT EDIT.

package destinations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/JunkieJI/travel-senpai/api/swagger/models"
)

// GetDestinationsOKCode is the HTTP code returned for type GetDestinationsOK
const GetDestinationsOKCode int = 200

/*GetDestinationsOK get destinations o k

swagger:response getDestinationsOK
*/
type GetDestinationsOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Destination `json:"body,omitempty"`
}

// NewGetDestinationsOK creates GetDestinationsOK with default headers values
func NewGetDestinationsOK() *GetDestinationsOK {
	return &GetDestinationsOK{}
}

// WithPayload adds the payload to the get destinations o k response
func (o *GetDestinationsOK) WithPayload(payload []*models.Destination) *GetDestinationsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get destinations o k response
func (o *GetDestinationsOK) SetPayload(payload []*models.Destination) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetDestinationsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make([]*models.Destination, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// GetDestinationsBadRequestCode is the HTTP code returned for type GetDestinationsBadRequest
const GetDestinationsBadRequestCode int = 400

/*GetDestinationsBadRequest get destinations bad request

swagger:response getDestinationsBadRequest
*/
type GetDestinationsBadRequest struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewGetDestinationsBadRequest creates GetDestinationsBadRequest with default headers values
func NewGetDestinationsBadRequest() *GetDestinationsBadRequest {
	return &GetDestinationsBadRequest{}
}

// WithPayload adds the payload to the get destinations bad request response
func (o *GetDestinationsBadRequest) WithPayload(payload string) *GetDestinationsBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get destinations bad request response
func (o *GetDestinationsBadRequest) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetDestinationsBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// GetDestinationsNotFoundCode is the HTTP code returned for type GetDestinationsNotFound
const GetDestinationsNotFoundCode int = 404

/*GetDestinationsNotFound get destinations not found

swagger:response getDestinationsNotFound
*/
type GetDestinationsNotFound struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewGetDestinationsNotFound creates GetDestinationsNotFound with default headers values
func NewGetDestinationsNotFound() *GetDestinationsNotFound {
	return &GetDestinationsNotFound{}
}

// WithPayload adds the payload to the get destinations not found response
func (o *GetDestinationsNotFound) WithPayload(payload string) *GetDestinationsNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get destinations not found response
func (o *GetDestinationsNotFound) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetDestinationsNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// GetDestinationsInternalServerErrorCode is the HTTP code returned for type GetDestinationsInternalServerError
const GetDestinationsInternalServerErrorCode int = 500

/*GetDestinationsInternalServerError get destinations internal server error

swagger:response getDestinationsInternalServerError
*/
type GetDestinationsInternalServerError struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewGetDestinationsInternalServerError creates GetDestinationsInternalServerError with default headers values
func NewGetDestinationsInternalServerError() *GetDestinationsInternalServerError {
	return &GetDestinationsInternalServerError{}
}

// WithPayload adds the payload to the get destinations internal server error response
func (o *GetDestinationsInternalServerError) WithPayload(payload string) *GetDestinationsInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get destinations internal server error response
func (o *GetDestinationsInternalServerError) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetDestinationsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}
