// Code generated by go-swagger; DO NOT EDIT.

package destinations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/JunkieJI/travel-senpai/api/swagger/models"
)

// UpdateDestinationOKCode is the HTTP code returned for type UpdateDestinationOK
const UpdateDestinationOKCode int = 200

/*UpdateDestinationOK update destination o k

swagger:response updateDestinationOK
*/
type UpdateDestinationOK struct {

	/*
	  In: Body
	*/
	Payload *models.Destination `json:"body,omitempty"`
}

// NewUpdateDestinationOK creates UpdateDestinationOK with default headers values
func NewUpdateDestinationOK() *UpdateDestinationOK {
	return &UpdateDestinationOK{}
}

// WithPayload adds the payload to the update destination o k response
func (o *UpdateDestinationOK) WithPayload(payload *models.Destination) *UpdateDestinationOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update destination o k response
func (o *UpdateDestinationOK) SetPayload(payload *models.Destination) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateDestinationOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdateDestinationBadRequestCode is the HTTP code returned for type UpdateDestinationBadRequest
const UpdateDestinationBadRequestCode int = 400

/*UpdateDestinationBadRequest update destination bad request

swagger:response updateDestinationBadRequest
*/
type UpdateDestinationBadRequest struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewUpdateDestinationBadRequest creates UpdateDestinationBadRequest with default headers values
func NewUpdateDestinationBadRequest() *UpdateDestinationBadRequest {
	return &UpdateDestinationBadRequest{}
}

// WithPayload adds the payload to the update destination bad request response
func (o *UpdateDestinationBadRequest) WithPayload(payload string) *UpdateDestinationBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update destination bad request response
func (o *UpdateDestinationBadRequest) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateDestinationBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// UpdateDestinationNotFoundCode is the HTTP code returned for type UpdateDestinationNotFound
const UpdateDestinationNotFoundCode int = 404

/*UpdateDestinationNotFound update destination not found

swagger:response updateDestinationNotFound
*/
type UpdateDestinationNotFound struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewUpdateDestinationNotFound creates UpdateDestinationNotFound with default headers values
func NewUpdateDestinationNotFound() *UpdateDestinationNotFound {
	return &UpdateDestinationNotFound{}
}

// WithPayload adds the payload to the update destination not found response
func (o *UpdateDestinationNotFound) WithPayload(payload string) *UpdateDestinationNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update destination not found response
func (o *UpdateDestinationNotFound) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateDestinationNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// UpdateDestinationInternalServerErrorCode is the HTTP code returned for type UpdateDestinationInternalServerError
const UpdateDestinationInternalServerErrorCode int = 500

/*UpdateDestinationInternalServerError update destination internal server error

swagger:response updateDestinationInternalServerError
*/
type UpdateDestinationInternalServerError struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewUpdateDestinationInternalServerError creates UpdateDestinationInternalServerError with default headers values
func NewUpdateDestinationInternalServerError() *UpdateDestinationInternalServerError {
	return &UpdateDestinationInternalServerError{}
}

// WithPayload adds the payload to the update destination internal server error response
func (o *UpdateDestinationInternalServerError) WithPayload(payload string) *UpdateDestinationInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update destination internal server error response
func (o *UpdateDestinationInternalServerError) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateDestinationInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}
