// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetTripByIDHandlerFunc turns a function with the right signature into a get trip by ID handler
type GetTripByIDHandlerFunc func(GetTripByIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetTripByIDHandlerFunc) Handle(params GetTripByIDParams) middleware.Responder {
	return fn(params)
}

// GetTripByIDHandler interface for that can handle valid get trip by ID params
type GetTripByIDHandler interface {
	Handle(GetTripByIDParams) middleware.Responder
}

// NewGetTripByID creates a new http.Handler for the get trip by ID operation
func NewGetTripByID(ctx *middleware.Context, handler GetTripByIDHandler) *GetTripByID {
	return &GetTripByID{Context: ctx, Handler: handler}
}

/*GetTripByID swagger:route GET /trips/{id} trip Trips getTripById

Trip By ID

*/
type GetTripByID struct {
	Context *middleware.Context
	Handler GetTripByIDHandler
}

func (o *GetTripByID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetTripByIDParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
