// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/JunkieJI/travel-senpai/api/swagger/models"
)

// GetTripByIDOKCode is the HTTP code returned for type GetTripByIDOK
const GetTripByIDOKCode int = 200

/*GetTripByIDOK get trip by Id o k

swagger:response getTripByIdOK
*/
type GetTripByIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.Trip `json:"body,omitempty"`
}

// NewGetTripByIDOK creates GetTripByIDOK with default headers values
func NewGetTripByIDOK() *GetTripByIDOK {
	return &GetTripByIDOK{}
}

// WithPayload adds the payload to the get trip by Id o k response
func (o *GetTripByIDOK) WithPayload(payload *models.Trip) *GetTripByIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get trip by Id o k response
func (o *GetTripByIDOK) SetPayload(payload *models.Trip) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTripByIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetTripByIDBadRequestCode is the HTTP code returned for type GetTripByIDBadRequest
const GetTripByIDBadRequestCode int = 400

/*GetTripByIDBadRequest get trip by Id bad request

swagger:response getTripByIdBadRequest
*/
type GetTripByIDBadRequest struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewGetTripByIDBadRequest creates GetTripByIDBadRequest with default headers values
func NewGetTripByIDBadRequest() *GetTripByIDBadRequest {
	return &GetTripByIDBadRequest{}
}

// WithPayload adds the payload to the get trip by Id bad request response
func (o *GetTripByIDBadRequest) WithPayload(payload string) *GetTripByIDBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get trip by Id bad request response
func (o *GetTripByIDBadRequest) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTripByIDBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// GetTripByIDNotFoundCode is the HTTP code returned for type GetTripByIDNotFound
const GetTripByIDNotFoundCode int = 404

/*GetTripByIDNotFound get trip by Id not found

swagger:response getTripByIdNotFound
*/
type GetTripByIDNotFound struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewGetTripByIDNotFound creates GetTripByIDNotFound with default headers values
func NewGetTripByIDNotFound() *GetTripByIDNotFound {
	return &GetTripByIDNotFound{}
}

// WithPayload adds the payload to the get trip by Id not found response
func (o *GetTripByIDNotFound) WithPayload(payload string) *GetTripByIDNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get trip by Id not found response
func (o *GetTripByIDNotFound) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTripByIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// GetTripByIDInternalServerErrorCode is the HTTP code returned for type GetTripByIDInternalServerError
const GetTripByIDInternalServerErrorCode int = 500

/*GetTripByIDInternalServerError get trip by Id internal server error

swagger:response getTripByIdInternalServerError
*/
type GetTripByIDInternalServerError struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewGetTripByIDInternalServerError creates GetTripByIDInternalServerError with default headers values
func NewGetTripByIDInternalServerError() *GetTripByIDInternalServerError {
	return &GetTripByIDInternalServerError{}
}

// WithPayload adds the payload to the get trip by Id internal server error response
func (o *GetTripByIDInternalServerError) WithPayload(payload string) *GetTripByIDInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get trip by Id internal server error response
func (o *GetTripByIDInternalServerError) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTripByIDInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}
