// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/JunkieJI/travel-senpai/api/swagger/models"
)

// GetDestinationByIDOKCode is the HTTP code returned for type GetDestinationByIDOK
const GetDestinationByIDOKCode int = 200

/*GetDestinationByIDOK get destination by Id o k

swagger:response getDestinationByIdOK
*/
type GetDestinationByIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.Destination `json:"body,omitempty"`
}

// NewGetDestinationByIDOK creates GetDestinationByIDOK with default headers values
func NewGetDestinationByIDOK() *GetDestinationByIDOK {
	return &GetDestinationByIDOK{}
}

// WithPayload adds the payload to the get destination by Id o k response
func (o *GetDestinationByIDOK) WithPayload(payload *models.Destination) *GetDestinationByIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get destination by Id o k response
func (o *GetDestinationByIDOK) SetPayload(payload *models.Destination) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetDestinationByIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetDestinationByIDBadRequestCode is the HTTP code returned for type GetDestinationByIDBadRequest
const GetDestinationByIDBadRequestCode int = 400

/*GetDestinationByIDBadRequest get destination by Id bad request

swagger:response getDestinationByIdBadRequest
*/
type GetDestinationByIDBadRequest struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewGetDestinationByIDBadRequest creates GetDestinationByIDBadRequest with default headers values
func NewGetDestinationByIDBadRequest() *GetDestinationByIDBadRequest {
	return &GetDestinationByIDBadRequest{}
}

// WithPayload adds the payload to the get destination by Id bad request response
func (o *GetDestinationByIDBadRequest) WithPayload(payload string) *GetDestinationByIDBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get destination by Id bad request response
func (o *GetDestinationByIDBadRequest) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetDestinationByIDBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// GetDestinationByIDNotFoundCode is the HTTP code returned for type GetDestinationByIDNotFound
const GetDestinationByIDNotFoundCode int = 404

/*GetDestinationByIDNotFound get destination by Id not found

swagger:response getDestinationByIdNotFound
*/
type GetDestinationByIDNotFound struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewGetDestinationByIDNotFound creates GetDestinationByIDNotFound with default headers values
func NewGetDestinationByIDNotFound() *GetDestinationByIDNotFound {
	return &GetDestinationByIDNotFound{}
}

// WithPayload adds the payload to the get destination by Id not found response
func (o *GetDestinationByIDNotFound) WithPayload(payload string) *GetDestinationByIDNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get destination by Id not found response
func (o *GetDestinationByIDNotFound) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetDestinationByIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// GetDestinationByIDInternalServerErrorCode is the HTTP code returned for type GetDestinationByIDInternalServerError
const GetDestinationByIDInternalServerErrorCode int = 500

/*GetDestinationByIDInternalServerError get destination by Id internal server error

swagger:response getDestinationByIdInternalServerError
*/
type GetDestinationByIDInternalServerError struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewGetDestinationByIDInternalServerError creates GetDestinationByIDInternalServerError with default headers values
func NewGetDestinationByIDInternalServerError() *GetDestinationByIDInternalServerError {
	return &GetDestinationByIDInternalServerError{}
}

// WithPayload adds the payload to the get destination by Id internal server error response
func (o *GetDestinationByIDInternalServerError) WithPayload(payload string) *GetDestinationByIDInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get destination by Id internal server error response
func (o *GetDestinationByIDInternalServerError) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetDestinationByIDInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}
