// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/JunkieJI/travel-senpai/api/swagger/models"
)

// GetTripsOKCode is the HTTP code returned for type GetTripsOK
const GetTripsOKCode int = 200

/*GetTripsOK get trips o k

swagger:response getTripsOK
*/
type GetTripsOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Trip `json:"body,omitempty"`
}

// NewGetTripsOK creates GetTripsOK with default headers values
func NewGetTripsOK() *GetTripsOK {
	return &GetTripsOK{}
}

// WithPayload adds the payload to the get trips o k response
func (o *GetTripsOK) WithPayload(payload []*models.Trip) *GetTripsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get trips o k response
func (o *GetTripsOK) SetPayload(payload []*models.Trip) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTripsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make([]*models.Trip, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// GetTripsBadRequestCode is the HTTP code returned for type GetTripsBadRequest
const GetTripsBadRequestCode int = 400

/*GetTripsBadRequest get trips bad request

swagger:response getTripsBadRequest
*/
type GetTripsBadRequest struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewGetTripsBadRequest creates GetTripsBadRequest with default headers values
func NewGetTripsBadRequest() *GetTripsBadRequest {
	return &GetTripsBadRequest{}
}

// WithPayload adds the payload to the get trips bad request response
func (o *GetTripsBadRequest) WithPayload(payload string) *GetTripsBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get trips bad request response
func (o *GetTripsBadRequest) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTripsBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// GetTripsNotFoundCode is the HTTP code returned for type GetTripsNotFound
const GetTripsNotFoundCode int = 404

/*GetTripsNotFound get trips not found

swagger:response getTripsNotFound
*/
type GetTripsNotFound struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewGetTripsNotFound creates GetTripsNotFound with default headers values
func NewGetTripsNotFound() *GetTripsNotFound {
	return &GetTripsNotFound{}
}

// WithPayload adds the payload to the get trips not found response
func (o *GetTripsNotFound) WithPayload(payload string) *GetTripsNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get trips not found response
func (o *GetTripsNotFound) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTripsNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// GetTripsInternalServerErrorCode is the HTTP code returned for type GetTripsInternalServerError
const GetTripsInternalServerErrorCode int = 500

/*GetTripsInternalServerError get trips internal server error

swagger:response getTripsInternalServerError
*/
type GetTripsInternalServerError struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewGetTripsInternalServerError creates GetTripsInternalServerError with default headers values
func NewGetTripsInternalServerError() *GetTripsInternalServerError {
	return &GetTripsInternalServerError{}
}

// WithPayload adds the payload to the get trips internal server error response
func (o *GetTripsInternalServerError) WithPayload(payload string) *GetTripsInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get trips internal server error response
func (o *GetTripsInternalServerError) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTripsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}
